name: gecko_internal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  lottie: ^3.1.3
  nfc_manager: ^3.5.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1 
  firebase_auth: ^5.3.1
  vibration: ^2.0.1
  permission_handler: ^11.3.1
  intl_phone_number_input: ^0.7.4
  geolocator: ^9.0.2
  number_ticker: ^0.0.2+1
  animated_digit: ^3.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/icons/
    - assets/images/
    - assets/sound/